import {clientIp} from '@/lib/auth';
import {contactMethods,deliveryMethods,type Delivery} from '@/lib/shop';
import {notifyOrder} from '@/lib/telegram';
import {db,getProducts,getStoreSettings,sameOrigin,jsonBody,textValue,response,safe,HttpError} from '@/lib/server';
export async function POST(r:Request){return safe(async()=>{sameOrigin(r);const v=await jsonBody(r);const id=textValue(v.id,36,36,'Номер заказа');if(!/^[a-f0-9-]{36}$/.test(id))throw new HttpError(400,'Обновите страницу.');if(await db().prepare('SELECT id FROM orders WHERE id=?').bind(id).first())return response({id,settings:await getStoreSettings()});const name=textValue(v.name,2,100,'Имя'),phone=textValue(v.phone,7,32,'Номер телефона');if(!/^\+?[\d\s()-]+$/.test(phone)||phone.replace(/\D/g,'').length<7||phone.replace(/\D/g,'').length>15)throw new HttpError(400,'Укажите номер телефона с кодом страны.');const contact=v.contactMethod==='whatsapp'?phone:textValue(v.contact,5,160,'Контакт'),comment=textValue(v.comment||'',0,1000,'Комментарий');const contactMethod=v.contactMethod===undefined?'':textValue(v.contactMethod,1,20,'Способ связи');if(contactMethod&&!contactMethods.some(x=>x.id===contactMethod))throw new HttpError(400,'Выберите WhatsApp, Telegram, ВК или MAX.');if(contactMethod==='whatsapp'&&(!/^\+?[\d\s()-]+$/.test(contact)||contact.replace(/\D/g,'').length<7||contact.replace(/\D/g,'').length>15))throw new HttpError(400,'Укажите номер WhatsApp с кодом страны.');const rulesAccepted=v.rulesAccepted===true||(v.rulesAccepted===undefined&&v.consent===true&&v.transferConsent===true&&v.offerConsent===true);if(v.website||!rulesAccepted)throw new HttpError(400,'Подтвердите, что ознакомились с правилами оформления заказа и принимаете их.');if(!Array.isArray(v.items)||v.items.length<1||v.items.length>50)throw new HttpError(400,'Проверьте корзину.');const settings=await getStoreSettings();
if(!v.delivery||typeof v.delivery!=='object'||!deliveryMethods.some(x=>x.id===v.delivery.method))throw new HttpError(400,'Выберите способ доставки.');
const delivery:Delivery={method:v.delivery.method,city:textValue(v.delivery.city||'',v.delivery.method==='pickup'?0:2,100,'Город'),address:textValue(v.delivery.address||'',v.delivery.method==='pickup'?0:3,300,'Адрес доставки'),productionConsent:v.delivery.productionConsent===true};
if(delivery.method==='pickup'){delivery.city='';delivery.address=settings.contactPickupAddress||settings.contactAddress;}
const products=await getProducts();const seen=new Set();const items=v.items.map((x:{id:string;quantity:number})=>{if(!x||typeof x!=='object')throw new HttpError(400,'Проверьте корзину.');const p=products.find(p=>p.id===x.id);if(!p||!p.available)throw new HttpError(409,'Один из товаров больше недоступен. Обновите каталог.');if(seen.has(x.id)||!Number.isInteger(x.quantity)||x.quantity<1||x.quantity>99)throw new HttpError(400,'Проверьте количество товаров.');seen.add(x.id);return {id:p.id,name:p.name,price:p.price,quantity:x.quantity};});const total=items.reduce((s:number,x:{price:number;quantity:number})=>s+x.price*x.quantity,0);if(v.total!==total)throw new HttpError(409,'Цены изменились. Обновите каталог перед заказом.');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(clientIp(r))))).map(x=>x.toString(16).padStart(2,'0')).join('');const since=new Date(Date.now()-300000).toISOString();const limit=await db().prepare('SELECT COUNT(*) AS n FROM orders WHERE client_hash=? AND created_at>?').bind(hash,since).first<{n:number}>();if(limit&&limit.n>=5)throw new HttpError(429,'Вы уже отправили несколько заказов. Повторите через 5 минут.');const saved=await db().prepare('INSERT OR IGNORE INTO orders (id,name,phone,contact,contact_method,comment,delivery,items,total,status,notified,client_hash,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,0,?,?)').bind(id,name,phone,contact,contactMethod,comment,JSON.stringify(delivery),JSON.stringify(items),total,'new',hash,new Date().toISOString()).run();if(saved.meta.changes)await notifyOrder(id);return response({id,settings:await getStoreSettings()},201);});}
