'use client';
import {useEffect,useState} from 'react';
import {Check,Loader2,RotateCcw} from 'lucide-react';
import {toast} from 'sonner';
import {contactGroups,type StoreSettings} from '@/lib/shop';
import {api,json} from '@/lib/client';
export default function ContactsEditor({settings,onSaved}:{settings:StoreSettings;onSaved:(settings:StoreSettings)=>Promise<void>}){
 const [draft,setDraft]=useState(settings),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!dirty)setDraft(settings)},[settings,dirty]);
 useEffect(()=>{if(!dirty)return;const stop=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop)},[dirty]);
 async function save(event:React.FormEvent){event.preventDefault();if(saving)return;setSaving(true);setError('');try{const r=await api('/api/admin/settings',json('PUT',{...draft,scope:'contacts'}));setDraft(r.settings);await onSaved(r.settings);setDirty(false);toast.success('Контакты обновлены на сайте и в документах')}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function reload(){if(dirty&&!window.confirm('Загрузить сохранённые контакты? Несохранённые правки в этой форме будут потеряны.'))return;setSaving(true);setError('');try{const r=await api('/api/admin/settings');setDraft(r.settings);await onSaved(r.settings);setDirty(false)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <div className="contacts-editor"><div className="content-heading"><h2>Контакты и соцсети</h2><p className="muted">Изменения появятся в магазине, при оформлении заказа и в реквизитах документов.</p></div><form className="form-stack" onSubmit={save}><fieldset disabled={saving} className="contacts-groups">{contactGroups.map(group=><section className="contact-settings-card form-stack" key={group.title}><h3>{group.title}</h3>{group.fields.map(field=><label key={field.key}>{field.label}{field.multiline?<textarea rows={3} maxLength={field.max} value={draft[field.key]} onChange={e=>{setDraft(p=>({...p,[field.key]:e.target.value}));setDirty(true)}}/>:<input type={field.key==='contactEmail'?'email':field.key==='contactPhone'?'tel':'text'} inputMode={field.key==='contactTaxId'?'numeric':undefined} maxLength={field.max} value={draft[field.key]} placeholder={field.key==='contactPhone'?'+7 900 123-45-67':field.key.startsWith('contact')&&['contactTelegram','contactPersonalTelegram','contactWhatsApp','contactVk','contactMax','contactInstagram'].includes(field.key)?'https://…':undefined} onChange={e=>{setDraft(p=>({...p,[field.key]:e.target.value}));setDirty(true)}}/>}{field.hint&&<span className="field-hint">{field.hint}</span>}</label>)}</section>)}</fieldset><p className="muted small">Пустые контакты и ссылки не показываются покупателям.</p>{error&&<p className="error-note" role="alert">{error}</p>}<div className="settings-save-bar"><span className="muted small" aria-live="polite">{dirty?'Есть несохранённые изменения':'Контакты сохранены'}</span><div><button type="button" className="secondary" disabled={saving} onClick={reload}><RotateCcw size={17}/>Вернуть сохранённое</button><button className="primary" disabled={saving||!dirty}>{saving?<Loader2 className="spin" size={17}/>:<Check size={17}/>}Сохранить контакты</button></div></div></form></div>;
}
