'use client';
import {useEffect,useRef,useState} from 'react';
import {Check,FolderPlus,ImagePlus,Loader2,Pencil,Plus,RotateCcw,Upload,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {toast} from 'sonner';
import {Category,Product,Banner,StoreSettings,storeTextGroups} from '@/lib/shop';
import {api,json} from '@/lib/client';
import ShopHero from '@/components/shop-hero';

export function StoreSettingsEditor({settings,onSaved}:{settings:StoreSettings;onSaved:(value:StoreSettings)=>Promise<void>}){
 const [draft,setDraft]=useState(settings),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!dirty)setDraft(settings)},[settings,dirty]);
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 function update(v:Partial<StoreSettings>){setDraft(p=>({...p,...v}));setDirty(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(saving)return;setSaving(true);setError('');try{const r=await api('/api/admin/settings',json('PUT',draft));setDraft(r.settings);await onSaved(r.settings);setDirty(false);toast.success('Настройки магазина сохранены')}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function reload(){if(saving)return;setSaving(true);setError('');try{const r=await api('/api/admin/settings');setDraft(r.settings);await onSaved(r.settings);setDirty(false)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <div className="store-settings"><div className="content-heading"><h2>Настройки магазина</h2><p className="muted">Название, тексты сайта и сообщение после заказа. Контакты и документы — в отдельных вкладках.</p></div><form onSubmit={save} onInvalid={e=>{const group=(e.target as HTMLElement).closest("details");if(group)group.open=true}} className="form-stack"><fieldset disabled={saving} className="form-stack"><label>Название магазина<input required maxLength={60} value={draft.name} onChange={e=>update({name:e.target.value})} placeholder="Название вашего магазина"/></label><p className="muted small">Появится в шапке, меню, внизу сайта и названии вкладки браузера.</p><div className="settings-divider"/><h3>Тексты сайта</h3><p className="muted small">Откройте нужный блок. Переносы строк сохраняются на сайте. Необязательные надписи можно оставить пустыми.</p><div className="store-text-groups">{storeTextGroups.map((group,i)=><details className="store-text-group" key={group.title} open={i===0}><summary>{group.title}</summary><div className="form-stack">{group.fields.map(field=><label key={field.key}>{field.label}{field.multiline?<textarea required={field.required} rows={field.max>200?4:2} maxLength={field.max} value={draft[field.key]} onChange={e=>update({[field.key]:e.target.value})}/>:<input required={field.required} maxLength={field.max} value={draft[field.key]} onChange={e=>update({[field.key]:e.target.value})}/>}</label>)}</div></details>)}</div><div className="settings-divider"/><h3>После оформления заказа</h3><label>Заголовок<input required maxLength={100} value={draft.orderSuccessTitle} onChange={e=>update({orderSuccessTitle:e.target.value})} placeholder="Спасибо за заказ"/></label><label>Сообщение покупателю<textarea required rows={5} maxLength={1200} value={draft.orderSuccessMessage} onChange={e=>update({orderSuccessMessage:e.target.value})} placeholder="Напишите, что будет дальше и как вы свяжетесь с покупателем"/></label><div className="confirmation-preview"><Check size={24}/><h3>{draft.orderSuccessTitle||'Заголовок'}</h3><p>{draft.orderSuccessMessage||'Сообщение покупателю'}</p><span className="muted small">Номер заказа добавится автоматически.</span></div></fieldset>{error&&<p className="error-note" role="alert">{error}</p>}<div className="store-settings-actions"><button type="button" className="secondary" disabled={saving} onClick={reload}><RotateCcw size={16}/>Вернуть сохранённое</button><button className="primary" disabled={saving||!dirty}>{saving?<Loader2 size={17} className="spin"/>:<Check size={17}/>}Сохранить настройки</button></div><p className="muted small" aria-live="polite">{dirty?'Есть несохранённые изменения':'Изменения сохранены'}</p></form></div>
}

export function CategoryManager({categories,products,onSaved}:{categories:Category[];products:Product[];onSaved:()=>Promise<void>}){
 const [name,setName]=useState(''),[editing,setEditing]=useState<Category|null>(null),[renamed,setRenamed]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState(''),[renameError,setRenameError]=useState(''),[removing,setRemoving]=useState<Category|null>(null),[moveTo,setMoveTo]=useState(''),[deleteError,setDeleteError]=useState('');
 const productCount=products.filter(p=>p.category===removing?.id).length;
 async function removeCategory(e:React.FormEvent){e.preventDefault();if(!removing||saving)return;setSaving(true);setDeleteError('');try{await api('/api/admin/categories/'+removing.id,json('DELETE',{updatedAt:removing.updatedAt,moveTo}));setRemoving(null);await onSaved();toast.success('Категория удалена, товары сохранены')}catch(e){setDeleteError((e as Error).message)}finally{setSaving(false)}}
 async function create(e:React.FormEvent){e.preventDefault();if(saving)return;setSaving(true);setError('');try{await api('/api/admin/categories',json('POST',{name}));setName('');await onSaved();toast.success('Категория добавлена')}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function rename(e:React.FormEvent){e.preventDefault();if(!editing||saving)return;setSaving(true);setRenameError('');try{await api('/api/admin/categories/'+editing.id,json('PUT',{name:renamed,updatedAt:editing.updatedAt}));setEditing(null);await onSaved();toast.success('Название категории обновлено')}catch(e){setRenameError((e as Error).message)}finally{setSaving(false)}}
 return <div className="category-manager"><div className="content-heading"><h2>Категории товаров</h2><p className="muted">Создайте раздел, затем выберите его в карточке товара.</p></div><form className="category-create form-stack" onSubmit={create}><label htmlFor="new-category">Новая категория<input id="new-category" value={name} onChange={e=>setName(e.target.value)} required maxLength={60} placeholder="Например, Подарочные наборы"/></label><button className="primary" disabled={saving||!name.trim()}>{saving?<Loader2 size={18} className="spin"/>:<Plus size={18}/>}Добавить категорию</button></form>{error&&<p className="error-note" role="alert">{error}</p>}<div className="category-list">{categories.map(c=><div className="category-row" key={c.id}><span className="category-symbol"><FolderPlus size={23}/></span><div><h3>{c.name}</h3><p className="muted small">Товаров: {products.filter(p=>p.category===c.id).length}</p></div><div className="category-actions"><button className="secondary" disabled={saving} onClick={()=>{setEditing(c);setRenamed(c.name);setRenameError('')}} aria-label={'Переименовать '+c.name}><Pencil size={16}/><span>Переименовать</span></button><button className="icon danger" disabled={saving} onClick={()=>{setRemoving(c);setMoveTo('');setDeleteError('')}} aria-label={'Удалить категорию '+c.name}><Trash2 size={18}/></button></div></div>)}</div><p className="muted small">Переименование обновляет название на сайте. Товары остаются в своей категории.</p>
 <Dialog open={!!editing} onOpenChange={o=>{if(!o&&!saving)setEditing(null)}}><DialogContent className="shop-dialog" onInteractOutside={e=>e.preventDefault()}><DialogTitle className="serif-title">Название категории</DialogTitle><DialogDescription>Новое название появится в каталоге и карточках товаров.</DialogDescription><form className="form-stack" onSubmit={rename}><label>Название<input required maxLength={60} value={renamed} onChange={e=>setRenamed(e.target.value)}/></label>{renameError&&<p className="error-note" role="alert">{renameError}</p>}<button className="primary" disabled={saving}>{saving?<Loader2 size={17} className="spin"/>:<Check size={17}/>}Сохранить</button></form></DialogContent></Dialog>
 <Dialog open={!!removing} onOpenChange={o=>{if(!o&&!saving)setRemoving(null)}}><DialogContent className="shop-dialog" onInteractOutside={e=>e.preventDefault()}><DialogTitle className="serif-title">Удалить «{removing?.name}»?</DialogTitle><DialogDescription>{productCount?`В категории товаров: ${productCount}. Перенесите их в другой раздел, затем категория будет удалена.`:'Пустая категория исчезнет из каталога и списка в форме товара.'}</DialogDescription><form className="form-stack" onSubmit={removeCategory}>{productCount>0&&(categories.some(c=>c.id!==removing?.id)?<label>Перенести товары в<Select value={moveTo} onValueChange={setMoveTo} disabled={saving}><SelectTrigger className="shop-select full"><SelectValue placeholder="Выберите категорию"/></SelectTrigger><SelectContent>{categories.filter(c=>c.id!==removing?.id).map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></label>:<p className="error-note">Сначала создайте другую категорию для переноса товаров.</p>)}{deleteError&&<p className="error-note" role="alert">{deleteError}</p>}<div className="category-delete-actions"><button type="button" className="secondary" disabled={saving} onClick={()=>setRemoving(null)}>Отмена</button><button className="primary delete-button" disabled={saving||(productCount>0&&!moveTo)}>{saving?<Loader2 size={17} className="spin"/>:<Trash2 size={17}/>}Удалить категорию</button></div></form></DialogContent></Dialog>
 </div>
}
export function BannerEditor({banner,onSaved}:{banner:Banner;onSaved:()=>Promise<void>}){
 const [draft,setDraft]=useState<Banner>(banner),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[view,setView]=useState('desktop');
 const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!dirty)setDraft(banner)},[banner,dirty]);
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 function update(v:Partial<Banner>){setDraft(p=>({...p,...v}));setDirty(true)}
 async function upload(file?:File){if(!file||saving||uploading)return;setUploading(true);setError('');try{if(file.size>8*1024*1024)throw new Error('Фото должно быть меньше 8 МБ.');const form=new FormData();form.append('file',file);const r=await api('/api/admin/upload',{method:'POST',body:form});update({image:r.url})}catch(e){setError((e as Error).message)}finally{setUploading(false);if(fileInput.current)fileInput.current.value=''}}
 async function save(e:React.FormEvent){e.preventDefault();if(saving||uploading)return;setSaving(true);setError('');try{const r=await api('/api/admin/banner',json('PUT',draft));setDraft(r.banner);await onSaved();setDirty(false);toast.success('Баннер обновлён на сайте')}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function reload(){setSaving(true);setError('');try{const r=await api('/api/admin/banner');setDraft(r.banner);await onSaved();setDirty(false)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <div className="banner-editor"><div className="content-heading"><h2>Главный баннер</h2><p className="muted">Загрузите фото, измените заголовок, описание, надпись и ссылку кнопки.</p></div><form onSubmit={save}><div className="banner-editor-grid"><div className="form-stack"><label>Надпись над заголовком<input maxLength={80} value={draft.eyebrow} onChange={e=>update({eyebrow:e.target.value})} placeholder="Можно оставить пустой"/></label><label>Заголовок<textarea required rows={3} maxLength={120} value={draft.title} onChange={e=>update({title:e.target.value})}/></label><label>Описание на баннере<textarea rows={3} maxLength={300} value={draft.description} onChange={e=>update({description:e.target.value})}/></label><h3 className="banner-button-heading">Кнопка на баннере</h3><div className="two-fields"><label>Надпись на кнопке<input maxLength={160} value={draft.buttonText} onChange={e=>update({buttonText:e.target.value})} placeholder="Смотреть каталог"/></label><label>Ссылка кнопки<input maxLength={300} value={draft.buttonLink} onChange={e=>update({buttonLink:e.target.value})} placeholder="#catalog"/></label></div><p className="muted small">#catalog открывает каталог, #delivery — доставку. Можно указать ссылку https://. Чтобы убрать кнопку, оставьте её текст пустым.</p><label>Описание фотографии<input maxLength={160} value={draft.imageAlt} onChange={e=>update({imageAlt:e.target.value})} placeholder="Что изображено на фото"/></label><div className="toggle-row"><div><b>Показывать баннер</b><p>Выключите, чтобы магазин начинался с каталога</p></div><Switch checked={draft.enabled} onCheckedChange={v=>update({enabled:v})} aria-label="Показывать баннер"/></div></div><div className="banner-image-editor"><div className="field-head"><b>Изображение баннера</b><ImagePlus size={19}/></div><img src={draft.image} alt={draft.imageAlt||'Фото баннера'}/><input ref={fileInput} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/><button type="button" className="secondary full" disabled={saving||uploading} onClick={()=>fileInput.current?.click()}>{uploading?<Loader2 className="spin" size={18}/>:<Upload size={18}/>} {uploading?'Загружаем…':'Загрузить баннер'}</button><p className="muted small">Рекомендуемый размер: 1920 × 1080 пикселей (16:9). JPG, PNG или WebP, до 8 МБ. Главный объект расположите ближе к центру. Текст и кнопка накладываются на фото по центру. На телефоне края изображения могут обрезаться.</p><div className="banner-save-info"><Check size={20}/><p>Фото и текст появятся на сайте после нажатия «Сохранить баннер».</p></div></div></div>
 <div className="banner-preview-head"><div><h3>Предпросмотр</h3><p className="muted small">{draft.enabled?'Так баннер будет выглядеть в магазине.':'Баннер скрыт. Ниже показан его макет.'}</p></div><div className="preview-size-buttons"><button type="button" className={view==='desktop'?'active':''} onClick={()=>setView('desktop')} aria-pressed={view==='desktop'}>Компьютер</button><button type="button" className={view==='mobile'?'active':''} onClick={()=>setView('mobile')} aria-pressed={view==='mobile'}>Телефон</button></div></div><div className={'banner-preview-frame '+(view==='mobile'?'mobile-preview':'desktop-preview')}><ShopHero banner={draft} preview/></div>
 {error&&<p className="error-note" role="alert">{error}</p>}<div className="banner-editor-footer"><span className="muted small" aria-live="polite">{dirty?'Есть несохранённые изменения':'Изменения сохранены'}</span><div><button type="button" className="secondary" disabled={saving||uploading} onClick={reload}><RotateCcw size={16}/>Вернуть сохранённое</button><button className="primary" disabled={saving||uploading||!dirty}>{saving?<Loader2 size={17} className="spin"/>:<Check size={17}/>} {saving?'Сохраняем…':'Сохранить баннер'}</button></div></div>
 </form></div>
}
