'use client';
import {useEffect,useState} from 'react';
import {Check,ExternalLink,FileText,Loader2,RotateCcw} from 'lucide-react';
import {toast} from 'sonner';
import {api,json} from '@/lib/client';
import type {StoreSettings} from '@/lib/shop';
import {legalPath,type LegalDocument} from '@/lib/legal-documents';
import {DocumentBody,SellerDetails} from '@/components/legal-content';
export default function DocumentsEditor({settings}:{settings:StoreSettings}){
 const [documents,setDocuments]=useState<LegalDocument[]>([]),[drafts,setDrafts]=useState<Record<string,LegalDocument>>({}),[selected,setSelected]=useState('offer'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(false);
 const current=documents.find(d=>d.slug===selected),draft=drafts[selected]||current;
 const dirty=!!current&&!!draft&&(current.title!==draft.title||current.body!==draft.body);
 const anyDirty=documents.some(d=>drafts[d.slug]&&(d.title!==drafts[d.slug].title||d.body!==drafts[d.slug].body));
 async function load(){setLoading(true);setError('');try{const r=await api('/api/admin/documents');setDocuments(r.documents)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!anyDirty)return;const stop=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop)},[anyDirty]);
 function update(changes:Partial<LegalDocument>){if(draft)setDrafts(p=>({...p,[selected]:{...draft,...changes}}))}
 async function save(event:React.FormEvent){event.preventDefault();if(!draft||saving)return;setSaving(true);setError('');try{const r=await api('/api/admin/documents/'+selected,json('PUT',draft));setDocuments(p=>p.map(d=>d.slug===selected?r.document:d));setDrafts(p=>({...p,[selected]:r.document}));toast.success('Документ сохранён на сайте')}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function reload(){if(dirty&&!window.confirm('Заменить несохранённый текст сохранённой версией документа?'))return;setSaving(true);setError('');try{const r=await api('/api/admin/documents/'+selected);setDocuments(p=>p.map(d=>d.slug===selected?r.document:d));setDrafts(p=>({...p,[selected]:r.document}))}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <div className="documents-editor"><div className="content-heading"><h2>Документы магазина</h2><p className="muted">Все четыре документа открываются на вашем сайте. Измените название и текст, затем сохраните.</p></div>{loading?<p className="documents-loading"><Loader2 size={20} className="spin"/>Загружаем документы…</p>:!documents.length?<div className="error-note">{error||'Не удалось загрузить документы.'}<button className="secondary" onClick={load}>Повторить</button></div>:<div className="documents-workspace"><nav className="document-selector" aria-label="Выбрать документ">{documents.map(doc=><button key={doc.slug} type="button" disabled={saving} className={selected===doc.slug?'selected':''} aria-pressed={selected===doc.slug} onClick={()=>{setSelected(doc.slug);setError('');setPreview(false)}}><FileText size={19}/><span>{doc.title}{drafts[doc.slug]&&(drafts[doc.slug].title!==doc.title||drafts[doc.slug].body!==doc.body)&&<small>Не сохранено</small>}</span></button>)}</nav>{draft&&<form className="document-editor-form form-stack" onSubmit={save}><div className="document-editor-toolbar"><div className="preview-size-buttons"><button type="button" className={!preview?'active':''} onClick={()=>setPreview(false)}>Редактировать</button><button type="button" className={preview?'active':''} onClick={()=>setPreview(true)}>Предпросмотр</button></div><a href={legalPath(selected)} target="_blank" rel="noreferrer"><ExternalLink size={16}/>Открыть на сайте</a></div>{!current?.updatedAt&&<p className="editor-help">Это начальный текст. Замените или дополните его условиями вашего магазина. Перед началом продаж проверьте документ и реквизиты.</p>}{preview?<div className="document-preview"><h1>{draft.title}</h1><DocumentBody body={draft.body}/><SellerDetails settings={settings}/></div>:<fieldset disabled={saving} className="form-stack"><label>Название документа<input required maxLength={180} value={draft.title} onChange={e=>update({title:e.target.value})}/></label><label>Текст документа<textarea className="document-textarea" required maxLength={100000} value={draft.body} onChange={e=>update({body:e.target.value})} placeholder="Вставьте полный текст документа"/></label><p className="muted small">Абзацы и переносы строк сохраняются. Для заголовка начните строку с ##. Реквизиты внизу обновляются из вкладки «Контакты».</p></fieldset>}{error&&<p role="alert" className="error-note">{error}</p>}<div className="settings-save-bar"><span className="muted small" aria-live="polite">{dirty?'Есть несохранённые изменения':current?.updatedAt?'Изменения сохранены':'Начальный текст'}</span><div><button type="button" className="secondary" disabled={saving} onClick={reload}><RotateCcw size={16}/>Вернуть сохранённое</button><button type="submit" className="primary" disabled={saving||!dirty&&!!current?.updatedAt}>{saving?<Loader2 className="spin" size={17}/>:<Check size={17}/>}Сохранить документ</button></div></div></form>}</div>}</div>;
}
