'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Pencil,Trash2,Upload,Loader2,Check,RefreshCw,ChevronUp,ChevronDown,MessageSquareQuote,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Switch} from '@/components/ui/switch';
import {api,json} from '@/lib/client';
import type {Review,ReviewSettings} from '@/lib/shop';
import {toast} from 'sonner';
export default function ReviewsEditor(){
 const [config,setConfig]=useState<ReviewSettings|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState('');
 const [edit,setEdit]=useState<Review|null>(null),[editDirty,setEditDirty]=useState(false),[discard,setDiscard]=useState(false),[removing,setRemoving]=useState<Review|null>(null),[uploading,setUploading]=useState(false),[editError,setEditError]=useState('');
 const input=useRef<HTMLInputElement>(null);
 async function load(){setLoading(true);setError('');try{const d=await api<{reviews:ReviewSettings}>('/api/admin/reviews');setConfig(d.reviews);setDirty(false)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!dirty&&!editDirty)return;const fn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty,editDirty]);
 function update(change:Partial<ReviewSettings>){setConfig(c=>c?{...c,...change}:c);setDirty(true)}
 function changeReview(change:Partial<Review>){setEdit(r=>r?{...r,...change}:r);setEditDirty(true)}
 function open(review?:Review){setEdit(review?{...review}:{id:crypto.randomUUID(),author:'',text:'',image:'',date:'',visible:true});setEditDirty(false);setEditError('')}
 function close(){if(uploading)return;if(editDirty)setDiscard(true);else setEdit(null)}
 async function upload(file?:File){if(!file)return;setUploading(true);setEditError('');try{if(file.size>8*1024*1024)throw new Error('Файл должен быть меньше 8 МБ.');const form=new FormData();form.append('file',file);const r=await api('/api/admin/upload',{method:'POST',body:form});changeReview({image:r.url})}catch(e){setEditError((e as Error).message)}finally{setUploading(false);if(input.current)input.current.value=''}}
 function apply(e:React.FormEvent){e.preventDefault();if(!config||!edit||uploading)return;if(!edit.text.trim()&&!edit.image){setEditError('Добавьте текст или фото отзыва.');return}update({items:config.items.some(x=>x.id===edit.id)?config.items.map(x=>x.id===edit.id?edit:x):[...config.items,edit]});setEdit(null);setEditDirty(false)}
 function move(index:number,direction:number){if(!config)return;const next=[...config.items],other=index+direction;if(other<0||other>=next.length)return;[next[index],next[other]]=[next[other],next[index]];update({items:next})}
 async function save(e:React.FormEvent){e.preventDefault();if(!config||saving)return;setSaving(true);setError('');try{const d=await api<{reviews:ReviewSettings}>('/api/admin/reviews',json('PUT',config));setConfig(d.reviews);setDirty(false);toast.success('Отзывы сохранены на сайте')}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <div className="reviews-editor"><div className="content-heading"><h2>Отзывы покупателей</h2><p className="muted">Загружайте готовые карточки отзывов и меняйте их порядок в галерее.</p></div>
 {loading?<div className="empty"><Loader2 className="spin"/>Загружаем отзывы…</div>:!config?<div className="error-note" role="alert">{error}<button className="secondary" onClick={load}>Повторить</button></div>:<form onSubmit={save} className="reviews-settings form-stack"><fieldset disabled={saving} className="form-stack"><label>Заголовок блока<input required maxLength={100} value={config.title} onChange={e=>update({title:e.target.value})}/></label><div className="toggle-row"><div><b>Показывать отзывы на сайте</b><p>Отдельный раздел под доставкой</p></div><Switch checked={config.enabled} onCheckedChange={enabled=>update({enabled})} aria-label="Показывать отзывы на сайте"/></div>
 <div className="reviews-admin-toolbar"><span className="muted small">Отзывов: {config.items.length} из 30</span><button type="button" className="secondary" disabled={config.items.length>=30} onClick={()=>open()}><Plus size={17}/>Добавить отзыв</button></div>
 {!config.items.length?<div className="reviews-admin-empty"><MessageSquareQuote size={32}/><p>Отзывы пока не добавлены.</p><p className="muted small">Добавьте отзыв и нажмите «Сохранить отзывы».</p></div>:<div className="reviews-admin-list">{config.items.map((r,i)=><article className="review-admin-row" key={r.id}>{r.image?<img src={r.image} alt="Фото отзыва"/>:<span className="review-admin-icon"><MessageSquareQuote/></span>}<div className="review-admin-copy"><strong>{r.author||'Покупатель'}</strong><p>{r.text||'Отзыв на фотографии'}</p><span className="muted small">{r.visible?'На сайте':'Скрыт'}{r.date?' · '+r.date:''}</span></div><div className="review-admin-actions"><button type="button" className="icon" aria-label="Переместить отзыв выше" disabled={i===0} onClick={()=>move(i,-1)}><ChevronUp size={17}/></button><button type="button" className="icon" aria-label="Переместить отзыв ниже" disabled={i===config.items.length-1} onClick={()=>move(i,1)}><ChevronDown size={17}/></button><button type="button" className="icon" aria-label="Редактировать отзыв" onClick={()=>open(r)}><Pencil size={17}/></button><button type="button" className="icon danger" aria-label="Удалить отзыв" onClick={()=>setRemoving(r)}><Trash2 size={17}/></button></div></article>)}</div>}
 </fieldset>{error&&<p className="error-note" role="alert">{error}</p>}<div className="store-settings-actions"><button type="button" className="secondary" disabled={saving} onClick={load}><RefreshCw size={16}/>Вернуть сохранённое</button><button className="primary" disabled={saving||!dirty}>{saving?<Loader2 size={17} className="spin"/>:<Check size={17}/>}Сохранить отзывы</button></div><p className="muted small" aria-live="polite">{dirty?'Есть несохранённые изменения':'Изменения сохранены'}</p></form>}
 <Dialog open={!!edit} onOpenChange={o=>{if(!o)close()}}><DialogContent className="shop-dialog review-editor-dialog" onInteractOutside={e=>e.preventDefault()}><DialogTitle>Отзыв покупателя</DialogTitle><DialogDescription>Изображение показывается целиком, без подписей. Текст служит описанием для озвучивания; без изображения он станет карточкой.</DialogDescription>{edit&&<form className="form-stack" onSubmit={apply}><fieldset disabled={uploading} className="form-stack"><label>Имя автора (для админпанели)<input maxLength={80} value={edit.author} onChange={e=>changeReview({author:e.target.value})} placeholder="Например, Анна"/></label><label>Текст отзыва / описание изображения<textarea rows={5} maxLength={2000} value={edit.text} onChange={e=>changeReview({text:e.target.value})}/></label><label>Дата или пометка (для админпанели)<input maxLength={60} value={edit.date} onChange={e=>changeReview({date:e.target.value})} placeholder="Например, сентябрь 2026"/></label>{edit.image&&<div className="review-upload-preview"><img src={edit.image} alt="Фото отзыва"/><button type="button" className="icon danger" aria-label="Убрать фотографию" onClick={()=>changeReview({image:''})}><X size={18}/></button></div>}<input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/><button type="button" className="secondary" onClick={()=>input.current?.click()}>{uploading?<Loader2 className="spin" size={17}/>:<Upload size={17}/>}Загрузить карточку отзыва</button><p className="muted small">JPG, PNG или WebP, до 8 МБ. Рекомендуется 1080 × 1920 пикселей (9:16). Карточка показывается целиком, без обрезки.</p><div className="toggle-row"><b>Показывать этот отзыв</b><Switch checked={edit.visible} onCheckedChange={visible=>changeReview({visible})} aria-label="Показывать этот отзыв"/></div></fieldset>{editError&&<p className="error-note" role="alert">{editError}</p>}<button className="primary" disabled={uploading}><Check size={17}/>Применить</button><p className="muted small">После этого сохраните список отзывов.</p></form>}</DialogContent></Dialog>
 <AlertDialog open={!!removing} onOpenChange={o=>{if(!o)setRemoving(null)}}><AlertDialogContent className="shop-dialog"><AlertDialogTitle>Удалить отзыв?</AlertDialogTitle><AlertDialogDescription>Он исчезнет с сайта после сохранения списка.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Отмена</AlertDialogCancel><AlertDialogAction className="delete-button" onClick={()=>{if(config&&removing)update({items:config.items.filter(x=>x.id!==removing.id)});setRemoving(null)}}>Удалить</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={discard} onOpenChange={setDiscard}><AlertDialogContent className="shop-dialog"><AlertDialogTitle>Закрыть без применения?</AlertDialogTitle><AlertDialogDescription>Правки этого отзыва ещё не добавлены в список.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Продолжить</AlertDialogCancel><AlertDialogAction onClick={()=>{setEdit(null);setEditDirty(false);setDiscard(false)}}>Закрыть</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
