'use client';
import {useEffect,useState} from 'react';
import {ShoppingBag,Menu,Leaf,MapPin,Phone,Mail} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Skeleton} from '@/components/ui/skeleton';
import {toast} from 'sonner';
import {Product,Category,Banner,StoreSettings,ReviewSettings,productPrice,orderTotal} from '@/lib/shop';
import {api} from '@/lib/client';
import ShopHero from '@/components/shop-hero';
import ShopSocials from '@/components/shop-socials';
import ReviewsSection from '@/components/reviews-section';
import CartLines from '@/components/cart-lines';
import {useCart} from '@/lib/use-cart';

export default function Shop({initialBanner,initialSettings,initialReviews,initialProducts,initialCategories}:{initialProducts:Product[];initialCategories:Category[];initialBanner:Banner;initialSettings:StoreSettings;initialReviews:ReviewSettings}){
 const [categories,setCategories]=useState<Category[]>(initialCategories),[banner,setBanner]=useState(initialBanner),[settings,setSettings]=useState(initialSettings),[reviews,setReviews]=useState(initialReviews);
 const categoryName=(id:string)=>categories.find(c=>c.id===id)?.name||'Каталог';
 const [products,setProducts]=useState<Product[]>(initialProducts),[loading,setLoading]=useState(!initialProducts.length),[error,setError]=useState('');
 const [category,setCategory]=useState('all'),[menu,setMenu]=useState(false),[product,setProduct]=useState<Product|null>(null),[photo,setPhoto]=useState(0);
 const {cart,setCart,ready}=useCart();const [cartOpen,setCartOpen]=useState(false);
 async function load(){setLoading(true);setError('');try{const d=await api('/api/products');setProducts(d.products);setCategories(d.categories);setBanner(d.banner);setSettings(d.settings);setReviews(d.reviews)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const lines=products.filter(p=>cart[p.id]).map(p=>({...p,quantity:cart[p.id]}));
 const count=lines.reduce((s,p)=>s+p.quantity,0),total=lines.reduce((s,p)=>s+p.price*p.quantity,0);
 const unavailable=lines.some(p=>!p.available)||Object.keys(cart).some(id=>!products.some(p=>p.id===id));
 function add(p:Product){if(!p.available||!ready)return;setCart(c=>({...c,[p.id]:Math.min(99,(c[p.id]||0)+1)}));toast.success('Товар добавлен в корзину');}
 function change(id:string,n:number){setCart(c=>{const out={...c};if(n<1)delete out[id];else out[id]=Math.min(99,n);return out});}
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>void}}).modelContext;if(!ctx)return;const ac=new AbortController();try{ctx.registerTool({name:'list_aromaty_products',description:'Показать текущие товары каталога.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>({products:await api('/api/products')})},{signal:ac.signal});ctx.registerTool({name:'open_aromaty_cart',description:'Открыть корзину для проверки. Не отправляет заказ.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>{setCartOpen(true);return {opened:true}}},{signal:ac.signal})}catch{}return()=>ac.abort()},[]);
 return <>
 <header className="shop-header"><button className="icon mobile-menu" aria-label="Открыть меню" onClick={()=>setMenu(true)}><Menu/></button><a href="/" className="brand">{settings.name}</a><nav><a href="#catalog">Товары</a><a href="#delivery">Доставка</a>{reviews.enabled&&<a href="#reviews">Отзывы</a>}<a href="#contacts">Контакты</a></nav><button className="cart-link" onClick={()=>{setCartOpen(true)}}><ShoppingBag size={22}/><span className="desktop-label">Корзина</span><span>({count})</span></button></header>
 <main><ShopHero banner={banner}/><div className="hero-socials"><ShopSocials settings={settings}/></div>
 <section id="catalog" className="catalog section"><div className="section-title">{settings.catalogEyebrow&&<p className="eyebrow">{settings.catalogEyebrow}</p>}<h2>{settings.catalogTitle}</h2>{settings.catalogDescription&&<p>{settings.catalogDescription}</p>}</div><div className="filters">{[['all','Все товары'],...categories.filter(c=>products.some(p=>p.category===c.id)).map(c=>[c.id,c.name])].map(([id,label])=><button className={category===id?'active':''} onClick={()=>setCategory(id)} key={id} aria-pressed={category===id}>{label}</button>)}</div>
 {loading&&!products.length?<div className="product-grid">{[1,2,3,4,5,6].map(i=><div key={i}><Skeleton className="aspect-square w-full"/><Skeleton className="mt-4 h-7 w-2/3"/></div>)}</div>:error?<div className="empty"><p role="alert">{error}</p><button className="secondary" onClick={load}>Попробовать ещё раз</button></div>:<div className="product-grid">{products.filter(p=>category==='all'||p.category===category).map(p=><article className="product-card" key={p.id}><button className="product-image" onClick={()=>{setProduct(p);setPhoto(0)}} aria-label={'Подробнее: '+p.name}><img src={p.images[0]} alt={p.name} loading="lazy"/>{p.images[1]&&<img className="product-hover-image" src={p.images[1]} alt="" loading="lazy"/>}{!p.available&&<span className="image-badge">Нет в наличии</span>}</button><div className="product-info"><p className="eyebrow">{categoryName(p.category)}</p><button className="product-name" onClick={()=>{setProduct(p);setPhoto(0)}}>{p.name}</button><div className="price-line"><span>{p.volume}</span><strong>{productPrice(p.price)}</strong></div><div className="product-actions"><button className="primary" onClick={()=>{setProduct(p);setPhoto(0)}}>Посмотреть</button><button className="secondary" disabled={!p.available} onClick={()=>add(p)}>{p.available?'В корзину':'Нет в наличии'}</button></div></div></article>)}</div>}
 {!loading&&!error&&!products.some(p=>category==='all'||p.category===category)&&<div className="empty">В этой категории пока нет товаров.</div>}</section>
 <section id="delivery" className="delivery section"><div className="section-title">{settings.deliveryEyebrow&&<p className="eyebrow">{settings.deliveryEyebrow}</p>}<h2>{settings.deliveryTitle}</h2>{settings.deliveryDescription&&<p>{settings.deliveryDescription}</p>}</div><div className="delivery-cards">{[{title:settings.deliveryPickupTitle,text:settings.deliveryPickupText,price:settings.deliveryPickupPrice},{title:settings.deliveryCourierTitle,text:settings.deliveryCourierText,price:settings.deliveryCourierPrice},{title:settings.deliveryShippingTitle,text:settings.deliveryShippingText,price:settings.deliveryShippingPrice}].filter(x=>x.title||x.text).map(({title,text,price},i)=><article className="delivery-card" key={i}><img src={'/images/kristal/delivery-'+(i+1)+'.png'} width={90} height={90} alt=""/>{title&&<h3>{title}</h3>}{price&&<b className="delivery-price">{price}</b>}{text&&<p>{text}</p>}</article>)}</div>{settings.productionText&&<p className="production-note">{settings.productionText}</p>}</section>
 <ReviewsSection reviews={reviews}/> <section id="about" className="about section"><Leaf strokeWidth={1} size={36}/>{settings.aboutEyebrow&&<p className="eyebrow">{settings.aboutEyebrow}</p>}<h2>{settings.aboutTitle}</h2>{settings.aboutDescription&&<p>{settings.aboutDescription}</p>}<p className="cooperation-social-label">Наши страницы в социальных сетях</p><ShopSocials settings={settings}/></section>
</main>
 <footer id="contacts" className="shop-footer"><a href="/" className="brand">{settings.name}</a>{settings.footerTagline&&<p className="footer-contact-title">{settings.footerTagline}</p>}{settings.contactPerson&&<p className="seller-name">{settings.contactPerson}</p>}<div className="shop-contact-details">{settings.contactPhone&&<a href={'tel:'+settings.contactPhone.replace(/[^\d+]/g,'')}><Phone size={19}/>{settings.contactPhone}</a>}{settings.contactEmail&&<a href={'mailto:'+settings.contactEmail}><Mail size={19}/>{settings.contactEmail}</a>}{settings.contactAddress&&<p><MapPin size={19}/>{settings.contactAddress}</p>}</div><div className="shop-socials">{[['telegram','Написать в Telegram',settings.contactPersonalTelegram||settings.contactTelegram],['whatsapp','Написать в WhatsApp',settings.contactWhatsApp],['max','Написать в MAX',settings.contactMax]].filter(x=>x[2]).map(([id,label,url])=><a href={url} key={id} target="_blank" rel="noreferrer"><img src={'/icons/'+id+(id==='max'?'.png':'.svg')} alt="" width={24} height={24}/><span>{label}</span></a>)}</div>{settings.contactTaxId&&<p className="seller-tax">ИНН {settings.contactTaxId}</p>}<nav className="legal-links" aria-label="Документы магазина">{[[settings.legalTitles?.['offer']||'Публичная оферта на товары',settings.legalOffer],[settings.legalTitles?.['privacy']||'Политика конфиденциальности',settings.legalPrivacy],[settings.legalTitles?.['data-consent']||'Согласие на обработку персональных данных',settings.legalDataConsent],[settings.legalTitles?.['transfer-consent']||'Согласие на передачу персональных данных',settings.legalTransferConsent]].filter(x=>x[1]).map(([label,url])=><a href={url} key={label}>{label}</a>)}</nav>{settings.footerNote&&<span className="footer-note">{settings.footerNote}</span>}<a href="#" className="back-to-top">Наверх ↑</a></footer>
 <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="shop-dialog"><DialogTitle>{settings.name}</DialogTitle><DialogDescription>Каталог, информация о магазине и доставка</DialogDescription><nav className="mobile-nav">{[['catalog','Товары'],['about','Сотрудничество'],['delivery','Доставка и оплата'],...(reviews.enabled?[['reviews','Отзывы']]:[]),['contacts','Контакты']].map(([id,t])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{t}</a>)}</nav></DialogContent></Dialog>
 <Dialog open={!!product} onOpenChange={o=>{if(!o)setProduct(null)}}><DialogContent className="shop-dialog product-dialog">{product&&<><div><img className="detail-image" src={product.images[photo]} alt={product.name}/>{product.images.length>1&&<div className="thumbs">{product.images.map((im,i)=><button key={im} className={i===photo?'selected':''} onClick={()=>setPhoto(i)} aria-label={'Фото '+(i+1)}><img src={im} alt=""/></button>)}</div>}</div><div className="detail-copy"><p className="eyebrow">{categoryName(product.category)}{product.volume&&<> · {product.volume}</>}</p><DialogTitle className="serif-title">{product.name}</DialogTitle><DialogDescription className="description">{product.description||'Подробности о товаре можно уточнить при подтверждении заказа.'}</DialogDescription><strong className="detail-price">{productPrice(product.price)}</strong>{settings.productionText&&<p className="detail-production">{settings.productionText}</p>}<button className="primary full" disabled={!product.available} onClick={()=>{add(product);setProduct(null);setCartOpen(true)}}>{product.available?'Добавить в корзину':'Нет в наличии'}</button></div></>}</DialogContent></Dialog>
 <Dialog open={cartOpen} onOpenChange={setCartOpen}><DialogContent className="shop-dialog cart-dialog"><DialogTitle className="serif-title">Ваша корзина</DialogTitle><DialogDescription>Товары, которые вы выбрали</DialogDescription>
 {!count&&!unavailable?<div className="empty"><ShoppingBag size={40} strokeWidth={1}/><p>Пока здесь пусто</p><DialogClose asChild><button className="primary">Перейти в каталог</button></DialogClose></div>:<>
 <CartLines lines={lines} onChange={change}/>
 {unavailable&&<div className="error-note">В корзине есть недоступные товары. <button onClick={()=>setCart(current=>Object.fromEntries(Object.entries(current).filter(([id])=>products.some(p=>p.id===id&&p.available))))}>Убрать их</button></div>}
 <div className="cart-total"><span>Итого</span><strong>{orderTotal(lines,total)}</strong></div><p className="muted small">Доставку, итоговую стоимость и оплату согласуем лично до подтверждения заказа.</p>
 {unavailable||!count?<button className="primary full" disabled>Оформить заказ</button>:<a className="primary full" href="/checkout">Оформить заказ</a>}
 </>}
 </DialogContent></Dialog>
 </>;
}
