import {localLegalLinks,legalPages} from './legal-documents';
import {ensureStoreContactUpdate} from './store-contact-update';
import {ensureReferenceContent,referenceImages,referenceBannerImage} from './reference-content';
import { env } from './runtime';
import {authenticated,configuredOrigin} from './auth';
import { Product,samples,Category,defaultCategories,Banner,defaultBanner,StoreSettings,defaultStoreSettings } from './shop';
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export function db(){if(!env.DB)throw new HttpError(503,'Хранилище временно недоступно. Попробуйте позже.');return env.DB;}
export function bucket(){if(!env.BUCKET)throw new HttpError(503,'Загрузка фото временно недоступна.');return env.BUCKET;}
export const isAdmin=authenticated;
export async function requireAdmin(){if(!await isAdmin())throw new HttpError(403,'Доступ разрешён только владельцу магазина.');}
export function sameOrigin(r:Request){if(r.headers.get('origin')!==configuredOrigin(r))throw new HttpError(403,'Обновите страницу и повторите действие.');}
export async function jsonBody(r:Request,maxLength=40000){const text=await r.text();if(text.length>maxLength)throw new HttpError(413,'Слишком много данных.');try{return JSON.parse(text)}catch{throw new HttpError(400,'Неверный формат запроса.')}}
export function response(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
export async function safe(fn:()=>Promise<Response>){try{return await fn()}catch(e){if(e instanceof HttpError)return response({error:e.message},e.status);console.error('Shop request failed',e instanceof Error?e.message:'unknown');return response({error:'Не удалось выполнить действие. Попробуйте ещё раз.'},503);}}
export function textValue(v:unknown,min:number,max:number,label:string){if(typeof v!=='string'||v.trim().length<min||v.trim().length>max)throw new HttpError(400,`Проверьте поле «${label}».`);return v.trim();}
export async function seed(){await seedCategories();const d=db();if(await d.prepare("SELECT key FROM settings WHERE key='seeded'").first())return;const now=new Date().toISOString();await d.batch([...samples.map(p=>d.prepare("INSERT OR IGNORE INTO products (id,name,description,category,volume,price,images,visible,available,created_at,updated_at) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key='seeded')").bind(p.id,p.name,p.description,p.category,p.volume,p.price,JSON.stringify(p.images),1,1,now,now)),d.prepare("INSERT OR IGNORE INTO settings (key,value) VALUES ('seeded','1')")]);}
export function parseProduct(r:Record<string,unknown>):Product{return {id:String(r.id),name:String(r.name),description:String(r.description),category:String(r.category),volume:String(r.volume),price:Number(r.price),images:JSON.parse(String(r.images)),visible:!!r.visible,available:!!r.available,updatedAt:String(r.updated_at)};}
export async function getProducts(admin=false){await ensureReferenceContent();await seed();const r=await db().prepare(`SELECT * FROM products ${admin?'':'WHERE visible=1'} ORDER BY created_at ASC`).all<Record<string,unknown>>();return r.results.map(parseProduct);}
export async function validateProduct(v:Record<string,unknown>){const name=textValue(v.name,1,100,'Название'),description=textValue(v.description,0,3000,'Описание'),volume=textValue(v.volume,0,80,'Характеристика');await seedCategories();if(typeof v.category!=='string'||!await db().prepare('SELECT id FROM categories WHERE id=?').bind(v.category).first())throw new HttpError(400,'Выберите существующую категорию.');if(!Number.isSafeInteger(v.price)||Number(v.price)<0||Number(v.price)>100000000)throw new HttpError(400,'Укажите цену от 0 до 1 000 000 ₽. Ноль — цена по запросу.');if(typeof v.visible!=='boolean'||typeof v.available!=='boolean')throw new HttpError(400,'Проверьте настройки товара.');if(!Array.isArray(v.images)||v.images.length<1||v.images.length>6||v.images.some(x=>typeof x!=='string'))throw new HttpError(400,'Добавьте от 1 до 6 фотографий.');for(const u of v.images as string[]){if(referenceImages.has(u)||['/images/diffuser.png','/images/car.png'].includes(u))continue;if(!/^\/api\/media\/[a-f0-9-]+\.(jpg|png|webp)$/.test(u)||!await db().prepare('SELECT key FROM uploads WHERE key=?').bind(u.slice('/api/media/'.length)).first())throw new HttpError(400,'Фотография не найдена. Загрузите её ещё раз.');}return {name,description,volume,category:v.category,price:Number(v.price),images:v.images as string[],visible:v.visible,available:v.available};}
export function categoryKey(name:string){return name.normalize('NFKC').trim().replace(/\s+/g,' ').toLocaleLowerCase('ru-RU');}
export async function seedCategories(){
 const d=db();if(await d.prepare("SELECT key FROM settings WHERE key='categories_seeded'").first())return;
 const now=new Date().toISOString();await d.batch([...defaultCategories.map((c,i)=>d.prepare("INSERT OR IGNORE INTO categories (id,name,name_key,position,updated_at) SELECT ?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key='categories_seeded')").bind(c.id,c.name,categoryKey(c.name),i,now)),d.prepare("INSERT OR IGNORE INTO settings (key,value) VALUES ('categories_seeded','1')")]);
}
export async function getCategories():Promise<Category[]>{await ensureReferenceContent();await seedCategories();const r=await db().prepare('SELECT id,name,updated_at FROM categories ORDER BY position,id').all<{id:string;name:string;updated_at:string}>();return r.results.map(c=>({id:c.id,name:c.name,updatedAt:c.updated_at}));}
export async function getBanner():Promise<Banner>{await ensureReferenceContent();const row=await db().prepare("SELECT value FROM settings WHERE key='banner_config'").first<{value:string}>();return row?{...defaultBanner,...JSON.parse(row.value)}:defaultBanner;}
export async function getStoreSettings():Promise<StoreSettings>{await ensureReferenceContent();await ensureStoreContactUpdate();const row=await db().prepare("SELECT value FROM settings WHERE key='store_config'").first<{value:string}>();const docs=await db().prepare("SELECT key,json_extract(value,'$.title') AS title FROM settings WHERE key LIKE 'legal_document:%'").all<{key:string;title:string}>();const legalTitles=Object.fromEntries(legalPages.map(p=>[p.slug,docs.results.find(d=>d.key==='legal_document:'+p.slug)?.title||p.title]));return {...defaultStoreSettings,...(row?JSON.parse(row.value):{}),...localLegalLinks,legalTitles};}
export async function validateBanner(v:Record<string,unknown>):Promise<Banner>{
 const title=textValue(v.title,1,120,'Заголовок'),eyebrow=textValue(v.eyebrow,0,80,'Надпись над заголовком'),description=textValue(v.description,0,300,'Текст баннера'),buttonText=textValue(v.buttonText,0,160,'Текст кнопки'),buttonLink=textValue(v.buttonLink,0,300,'Ссылка кнопки'),imageAlt=textValue(v.imageAlt,0,160,'Описание фото');
 if(typeof v.enabled!=='boolean')throw new HttpError(400,'Проверьте видимость баннера.');
 if(buttonText){let valid=false;try{const u=new URL(buttonLink,'https://shop.local');valid=!!buttonLink&&!/[\\\s\u0000-\u001f\u007f]/.test(buttonLink)&&!buttonLink.startsWith('//')&&((buttonLink.startsWith('/')||buttonLink.startsWith('#'))?u.origin==='https://shop.local':u.protocol==='https:');}catch{}if(!valid)throw new HttpError(400,'Ссылка кнопки должна начинаться с #, / или https://.');}
 const image=textValue(v.image,1,200,'Фото баннера');if(image!==referenceBannerImage&&!['/images/hero.png','/images/diffuser.png','/images/car.png'].includes(image)){if(!/^\/api\/media\/[a-f0-9-]+\.(jpg|png|webp)$/.test(image)||!await db().prepare('SELECT key FROM uploads WHERE key=?').bind(image.slice('/api/media/'.length)).first())throw new HttpError(400,'Загрузите фото баннера ещё раз.');}
 return {title,eyebrow,description,buttonText,buttonLink,image,imageAlt,enabled:v.enabled,version:crypto.randomUUID()};
}
