export type Product={id:string;name:string;description:string;category:string;volume:string;price:number;images:string[];visible:boolean;available:boolean;updatedAt?:string};
export type ContactMethod='whatsapp'|'telegram'|'vk'|'max';
export const contactMethods:{id:ContactMethod;label:string;placeholder:string}[]=[{id:'whatsapp',label:'WhatsApp',placeholder:'+7 999 123-45-67'},{id:'telegram',label:'Telegram',placeholder:'@username или номер телефона'},{id:'vk',label:'ВК',placeholder:'Ссылка на профиль или ID ВКонтакте'},{id:'max',label:'MAX',placeholder:'Номер телефона или ссылка на профиль'}];
export function contactMethodLabel(method:string){return contactMethods.find(x=>x.id===method)?.label||'Контакт'}
export type Delivery={method:string;city:string;address:string;productionConsent:boolean};
export const deliveryMethods=[{id:"pickup",label:"Самовывоз"},{id:"courier",label:"Курьер"},{id:"cdek",label:"СДЭК · пункт выдачи"},{id:"post",label:"Почта России"},{id:"other",label:"Другая служба"}];
export function deliveryLabel(id:string){return deliveryMethods.find(x=>x.id===id)?.label||id}
export type Order={delivery?:Delivery;id:string;name:string;phone:string;contact:string;contact_method:string;comment:string;items:{id:string;name:string;price:number;quantity:number}[];total:number;status:string;notified:number;created_at:string};
export const money=(n:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:2}).format(n/100);
export const productPrice=(n:number)=>n===0?'Цена по запросу':money(n);
export function orderTotal(items:{price:number}[],total:number){return items.some(x=>x.price===0)?(total?money(total)+' + позиции по запросу':'Стоимость по запросу'):money(total)}
export type Category={id:string;name:string;updatedAt:string};
export type TelegramSettings={hasToken:boolean;chatId:string;enabled:boolean;botUsername:string;version:string;canConfigure:boolean};
export type StoreText={contactLegalAddress:string;contactPickupAddress:string;contactInstagram:string;contactPersonalTelegram:string;contactPerson:string;contactTaxId:string;deliveryPickupPrice:string;deliveryCourierPrice:string;deliveryShippingPrice:string;productionText:string;legalOffer:string;legalPrivacy:string;legalDataConsent:string;legalTransferConsent:string;catalogEyebrow:string;catalogTitle:string;catalogDescription:string;aboutEyebrow:string;aboutTitle:string;aboutDescription:string;deliveryEyebrow:string;deliveryTitle:string;deliveryDescription:string;footerTagline:string;footerNote:string;deliveryPickupTitle:string;deliveryPickupText:string;deliveryCourierTitle:string;deliveryCourierText:string;deliveryShippingTitle:string;deliveryShippingText:string;contactPhone:string;contactEmail:string;contactAddress:string;contactTelegram:string;contactVk:string;contactMax:string;contactWhatsApp:string};
export const defaultStoreText:StoreText={contactLegalAddress:"",contactPickupAddress:"",contactInstagram:"",contactPersonalTelegram:"",contactPerson:"",contactTaxId:"",deliveryPickupPrice:"",deliveryCourierPrice:"",deliveryShippingPrice:"",productionText:"",legalOffer:"",legalPrivacy:"",legalDataConsent:"",legalTransferConsent:"",catalogEyebrow:'КАТАЛОГ',catalogTitle:'Выберите то, что вам нравится',catalogDescription:'Смотрите товары по категориям и добавляйте понравившееся в корзину.',aboutEyebrow:'О МАГАЗИНЕ',aboutTitle:'Для себя\nи близких',aboutDescription:'Здесь можно посмотреть товары и оставить заявку.\nВсе детали заказа обсудим лично.',deliveryEyebrow:'ПРОСТОЙ ЗАКАЗ',deliveryTitle:'Выберите. Оставьте контакт.\nОстальное обсудим лично.',deliveryDescription:'Добавьте товары в корзину и оформите заказ. Продавец свяжется с вами, уточнит наличие, удобный способ доставки и оплату.',footerTagline:'Товары для вас и ваших близких',footerNote:'Заказ и доставка — по договорённости',deliveryPickupTitle:'Самовывоз',deliveryPickupText:'Уточните у продавца возможность самовывоза, место и удобное время.',deliveryCourierTitle:'Курьером',deliveryCourierText:'Возможность, стоимость и сроки доставки обсудим при подтверждении заказа.',deliveryShippingTitle:'В другой город',deliveryShippingText:'Уточните доступные способы отправки. Стоимость зависит от адреса и выбранной службы.',contactPhone:'',contactEmail:'',contactAddress:'',contactTelegram:'',contactVk:'',contactMax:'',contactWhatsApp:''};
export const storeTextGroups:{title:string;fields:{key:keyof StoreText;label:string;max:number;required?:boolean;multiline?:boolean}[]}[]=[
 {title:'Надписи над каталогом',fields:[{key:'catalogEyebrow',label:'Надпись над заголовком',max:80},{key:'catalogTitle',label:'Заголовок каталога',max:160,required:true,multiline:true},{key:'catalogDescription',label:'Описание каталога',max:1200,multiline:true}]},
 {title:'Блок «О нас» под каталогом',fields:[{key:'aboutEyebrow',label:'Надпись над заголовком',max:80},{key:'aboutTitle',label:'Заголовок',max:160,required:true,multiline:true},{key:'aboutDescription',label:'Описание',max:1200,multiline:true}]},
 {title:'Доставка и оформление заказа',fields:[{key:'deliveryEyebrow',label:'Надпись над заголовком',max:80},{key:'deliveryTitle',label:'Заголовок',max:160,required:true,multiline:true},{key:'deliveryDescription',label:'Описание',max:1200,multiline:true}]},
 {title:'Карточки доставки',fields:[{key:'productionText',label:'Срок изготовления заказа',max:200},{key:'deliveryPickupPrice',label:'Самовывоз: стоимость',max:60},{key:'deliveryCourierPrice',label:'Курьер: стоимость',max:60},{key:'deliveryShippingPrice',label:'Отправка: стоимость',max:60},{key:'deliveryPickupTitle',label:'Первая карточка: заголовок',max:80},{key:'deliveryPickupText',label:'Первая карточка: описание',max:500,multiline:true},{key:'deliveryCourierTitle',label:'Вторая карточка: заголовок',max:80},{key:'deliveryCourierText',label:'Вторая карточка: описание',max:500,multiline:true},{key:'deliveryShippingTitle',label:'Третья карточка: заголовок',max:80},{key:'deliveryShippingText',label:'Третья карточка: описание',max:500,multiline:true}]},
 {title:'Надписи в самом низу сайта',fields:[{key:'footerTagline',label:'Первая надпись',max:200,multiline:true},{key:'footerNote',label:'Вторая надпись',max:200,multiline:true}]}
];
export const contactGroups:{title:string;fields:{key:keyof StoreText;label:string;max:number;multiline?:boolean;hint?:string}[]}[]=[
 {title:'Контакты магазина',fields:[{key:'contactPhone',label:'Номер телефона',max:32},{key:'contactEmail',label:'Электронная почта',max:120},{key:'contactAddress',label:'Адрес магазина',max:300,multiline:true},{key:'contactPickupAddress',label:'Адрес самовывоза',max:300,multiline:true,hint:'Появится при оформлении заказа. Если пусто, используется адрес магазина.'}]},
 {title:'Реквизиты продавца',fields:[{key:'contactPerson',label:'ФИО продавца или название организации',max:120},{key:'contactTaxId',label:'ИНН',max:20},{key:'contactLegalAddress',label:'Полный адрес продавца для документов',max:500,multiline:true,hint:'Автоматически показывается под текстом оферты, политики и согласий.'}]},
 {title:'Связь с продавцом',fields:[{key:'contactPersonalTelegram',label:'Личный Telegram',max:300,hint:'Например, https://t.me/username'},{key:'contactWhatsApp',label:'WhatsApp',max:300,hint:'Например, https://wa.me/79001234567'},{key:'contactMax',label:'MAX',max:300,hint:'Полная ссылка на профиль в MAX.'}]},
 {title:'Социальные сети магазина',fields:[{key:'contactTelegram',label:'Telegram-канал',max:300},{key:'contactVk',label:'ВКонтакте',max:300},{key:'contactInstagram',label:'Instagram',max:300}]}
];
export type StoreSettings=StoreText&{legalTitles?:Record<string,string>;name:string;orderSuccessTitle:string;orderSuccessMessage:string;version:string};
export const defaultStoreSettings:StoreSettings={...defaultStoreText,name:'МАГАЗИН',orderSuccessTitle:'Спасибо за заказ',orderSuccessMessage:'Мы свяжемся с вами по указанному контакту.\nОплату и доставку согласуем лично.',version:'initial'};
export const defaultCategories:Category[]=[{id:'home',name:'Для дома',updatedAt:''},{id:'car',name:'Для автомобиля',updatedAt:''}];
export type Banner={eyebrow:string;title:string;description:string;buttonText:string;buttonLink:string;image:string;imageAlt:string;enabled:boolean;version:string};
export const defaultBanner:Banner={eyebrow:'НАШ МАГАЗИН',title:'Найдите то,\nчто вам нравится',description:'Посмотрите товары и выберите то, что подходит именно вам.',buttonText:'Смотреть каталог',buttonLink:'#catalog',image:'/images/hero.png',imageAlt:'Диффузоры и автопарфюм на каменной подставке',enabled:true,version:'initial'};
export const statusLabels:Record<string,string>={new:'Новый',processing:'В работе',done:'Завершён',cancelled:'Отменён'};
export const samples:Product[]=[
 {id:'sample-cedar',name:'Сандал и кедр',description:'Тёплая древесная композиция с мягкими нотами сандала и сухого кедра. Для спокойных вечеров и любимых пространств.',category:'home',volume:'100 мл',price:149000,images:['/images/diffuser.png'],visible:true,available:true},
 {id:'sample-bergamot',name:'Бергамот',description:'Свежий цитрусовый аромат с лёгкой древесной основой. Небольшой флакон с деревянной крышкой для вашего автомобиля.',category:'car',volume:'8 мл',price:49000,images:['/images/car.png'],visible:true,available:true}
];

export type Review={id:string;author:string;text:string;image:string;date:string;visible:boolean};
export type ReviewSettings={title:string;enabled:boolean;items:Review[];version:string};
export const defaultReviewSettings:ReviewSettings={title:'Отзывы покупателей',enabled:true,items:[],version:'initial'};
